"""init

Revision ID: 00f6d536f2a1
Revises: 
Create Date: 2026-02-15 22:35:14.093140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f6d536f2a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='check_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='check_longitude_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_building_coords', 'building', ['latitude', 'longitude'], unique=False)
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['business.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', name='uq_name_parent')
    )
    op.create_index(op.f('ix_business_parent_id'), 'business', ['parent_id'], unique=False)
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_organization_name', 'organization', ['name'], unique=False)
    op.create_index(op.f('ix_organization_building_id'), 'organization', ['building_id'], unique=False)
    op.create_table('organization_business',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'business_id')
    )
    op.create_index('idx_org_business_business', 'organization_business', ['business_id'], unique=False)
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'organization_id', name='uq_number_organization')
    )
    op.create_index(op.f('ix_phone_organization_id'), 'phone', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_organization_id'), table_name='phone')
    op.drop_table('phone')
    op.drop_index('idx_org_business_business', table_name='organization_business')
    op.drop_table('organization_business')
    op.drop_index(op.f('ix_organization_building_id'), table_name='organization')
    op.drop_index('idx_organization_name', table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_business_parent_id'), table_name='business')
    op.drop_table('business')
    op.drop_index('idx_building_coords', table_name='building')
    op.drop_table('building')
    # ### end Alembic commands ###
